version: "3.7"

services:
  db:
    image: postgres:11.6
    hostname: db.localdomain
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      default:
        aliases:
          - db.localdomain
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: ./
    restart: "unless-stopped"
    command: python /code/manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/code:delegated
    ports:
      - "8000:80"
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - .env

  adminer:
    restart: "unless-stopped"
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

networks:
  default:
    ipam:
      config:
        - subnet: 172.16.23.0/24

volumes:
  pg_data: {}
