[tool.black]
line-length = 100
exclude = '(migrations|snapshots)'

[tool.pylint.MASTER]
extension-pkg-whitelist = "math"
load-plugins = "pylint_django,pylint.extensions.no_self_use"
ignore = "conftest.py,apps.py,__tests__,migrations,settings"
jobs = 6

[tool.pylint.FORMAT]
max-line-length = 100

[tool.pylint.'MESSAGES CONTROL']
disable = "missing-docstring,invalid-name,unused-argument,too-few-public-methods,no-self-use,logging-fstring-interpolation,line-too-long,too-many-locals,no-self-argument,redefined-builtin,no-name-in-module"

[tool.pylint.DESIGN]
max-parents = 13
